### ISSUE TITLE
warnings/errors on php7.2

### ISSUE THREAD

**Issue by Joduai** [BlakesHeaven/Simple-Stats-Plus#1]
Hi

Some time ago after updating bludit with enabled debug mode I found out that this plugin throws some warnings and notices on php 7.2.
I'm not sure if it is a matter of my webhost who disabled all "manual" ways of changing php.ini despite those set it webadmin panel, but just to let  you know:

```

Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /bl-kernel/helpers/session.class.php on line 11

Warning: session_set_cookie_params(): Cannot change session cookie parameters when session is active in /bl-kernel/helpers/session.class.php on line 27

Warning: session_name(): Cannot change session name when session is active in /bl-kernel/helpers/session.class.php on line 31

Notice: session_start(): A session had already been started - ignoring in /bl-kernel/helpers/session.class.php on line 34


Warning: Use of undefined constant adler32 - assumed 'adler32' (this will throw an Error in a future version of PHP) in /bl-plugins/simple-stats/plugin.php on line 306

Warning: Use of undefined constant enableOngoingCounter - assumed 'enableOngoingCounter' (this will throw an Error in a future version of PHP) in /bl-plugins/simple-stats/plugin.php on line 327

Notice: Unknown: Skipping numeric key 65591473 in Unknown on line 0
```

The strangest thing is last notice, as I have no idea what's the numeric key responsible for.

**Comment by BlakesHeaven** [comment]
Thanks very much for letting me know - I have never enabled debug mode in Bludit before - maybe I should try it :-)

**Comment by BlakesHeaven** [comment]
Hi @Joduai, I hope you'll see fewer warnings now, but please let me know if you spot anything else.

**Comment by Joduai** [comment]
Just had some spare time to update and check.
Everything's working fine, no php warnings or notices :)
