### ISSUE TITLE
Initilising the runningTotalsFile file - it look like it is not there

### ISSUE THREAD

**Issue by RalfKerkhoff** [BlakesHeaven/Simple-Stats-Plus#10]
Hi,

i get the Error  message above when enabling the ongoing counter.

It seems like it looks for a file named:
running-totals.json
under bl-content/workspaces/simple-stats-plus

which is actually not there.

Cheers
Ralf

**Comment by BlakesHeaven** [comment]
Hi, As a mater of interest which version is this in? 
If off the Bludit Plugins page please try from here shortly, [v3.13.1](https://github.com/BlakesHeaven/Simple-Stats-Plus/releases/tag/v3.13.1) as I am waiting on a Pull Request on Bludit site.

In any case, there was an issue for first time use with a few too many throw errors...

This was auto closed on commit - I'm just rereleasing it on the above link so I don't have to redo the above mentioned pull request.

Thanks for reporting it.

**Comment by RalfKerkhoff** [comment]
Hi,

version 3.13.1 was the one making problems.

Thanks for fixing it.

Cheers
Ralf
