### ISSUE TITLE
Required module: php-intl

### ISSUE THREAD

**Issue by cheesington** [BlakesHeaven/Simple-Stats-Plus#6]
Hey, thanks for the plugin.

I found that installing it on my admittedly basic system produced this error in the apache logs when loading the dashboard:

> ... PHP Fatal error:  Uncaught Error: Class 'NumberFormatter' not found in /var/www/boat/bl-plugins/simple-stats-plus/plugin.php:155 ...

Installing php-intl module cleared that up.  Maybe list as a requirement?

**Comment by BlakesHeaven** [comment]
Thanks for the advice, that is good to know.
I'll leave this open until I've added some suitable warning text.
