### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by xcme** [BlakesHeaven/Simple-Stats-Plus#7]
Hi!
I installed this plugin and disabled the native ones but it didn't show any stats. Three week have passes since than. What should I check to fix it?

**Comment by BlakesHeaven** [comment]
Hi, Try some of the following:
- Check for txt files in `/bl-content/workspaces/simple-stats-plus/`, these contain a line for each count to be displayed on the Admin Dashboard chart.
- The attributes of the above on mine is 755
- Check the settings are not set to delete files too early; below are mine, but the default ones should be ok for a start.
![image](https://user-images.githubusercontent.com/37149377/74091529-5e005100-4ab0-11ea-9da6-f295224e78ab.png)
Can you post back a screenshot of your settings and your dashboard - mine is below:
![image](https://user-images.githubusercontent.com/37149377/74091988-2a282a00-4ab6-11ea-8b75-2965814a6fa7.png)

**Comment by xcme** [comment]
Thank you for answer. My dashboard is below:
![image](https://user-images.githubusercontent.com/10675508/74179084-27fcd180-4c56-11ea-9c6a-a10345e12ab0.png)
There is no graph below like you just showed.

Yes, I have files here /bl-content/workspaces/simple-stats-plus/. They have **644** permissions and contain lines with hash and date. I changed the permissions to **755** but it didn't help.

I use the 3.10.0 version on Bludit.

**Comment by xcme** [comment]
I can add there is no more HTML code after this section:
![image](https://user-images.githubusercontent.com/10675508/74179788-8eceba80-4c57-11ea-8c01-f6a54a138146.png)
It seems something went wrong and page wasn't constructed properly. In case I turn native plugins back it has following lines with stats and "</body </html" at the end.

**Comment by BlakesHeaven** [comment]
Thanks, and sorry for slow reply.
May I ask what active plugins you have?
I'm thinking that maybe I have something activated that you don't that is finishing the closing tags off, thus making it work for me.
I did have an issue at one point where the Search plugin was causing mine to fail.

**Comment by xcme** [comment]
All my plugins are here:
![image](https://user-images.githubusercontent.com/10675508/74811655-5d1abb00-530b-11ea-983f-1ef2f6779988.png)

I noticed when I disable 'Simple Stats Plus' the dashboard page seems correctly and I can see the 'Notification' section. But when I enable 'Simple Stats Plus' it seems something goes wrong ether in the plugin itself or during its inclusion to the site. I tried to enable logs in PHP but I have Centos 7, so I had to use non-typical installation of PHP (rh-php72-php-fpm), so PHP works but I have no idea why logs don't work.

**Comment by BlakesHeaven** [comment]
Thanks very much. I'll look into it tonight.
I think it is still collecting stats though.

**Comment by BlakesHeaven** [comment]
Hello,
I have given the code a review, comparing it back the original and I couldn't see anything obvious.
I made it so I have exactly the same plugins activated as you have and my dashboard still displays OK.
In the code, I use an international format function requiring the "PHP-Intl" module as referenced in issue #6 . You say you have a non-standard installation of PHP; can you see if installing the PHP-Intl module helps.  
https://www.php.net/manual/en/intl.installation.php
https://stackoverflow.com/questions/14679990/how-do-i-install-php-intl-extension-on-centos

Below is the generated html:
![image](https://user-images.githubusercontent.com/37149377/74885721-2fb32900-536e-11ea-8a26-e375a7e53ad5.png)

**Comment by xcme** [comment]
Yes! When I installed it and restarted the engine, it started to work.
I issued:
`yum install rh-php72-php-intl`
on Centos 7.

Thank you for help!

**Comment by BlakesHeaven** [comment]
That's brilliant,  I really pleased 😎👍
Thanks for sticking with it.
BTW, I've been doing a little tinkering and am adding individual page counting. Got it doing the data capture; just need to work it into the Contents tab navigation or maybe something to display on an end of page hook.
